version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached
    command: sleep infinity
    depends_on:
      - mariadb
    networks:
      - default

  mariadb:
    image: mariadb:10.8
    ports:
      - "33062:3306"
    volumes:
      - aurora_aauth_mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=aauth
      - MYSQL_PASSWORD=aauth
      - MYSQL_USER=aauth
      - MYSQL_DATABASE=aauth
    networks:
      - default

volumes:
  aurora_aauth_mariadb_data:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.58.0/24 # Changed subnet to avoid conflict with existing one
